- name: print vault passowrd
  hosts: all
  gather_facts: false
  connection: local
  vars_files:
    - "../vault.yml"
  tasks:
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5
    - name: Print the vault password
      ansible.builtin.debug:
        msg: testing
    - name: Display runner contents
      command: ls /runner/project
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"